version: '3.8'

services:
  http:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - script
      - data

  script:
    image: wordpress:fpm-alpine
    volumes:
      - ./app:/app

  data:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
