version: '3.8'

services:
  http:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - script

  script:
    build:
      context: ./config/php
    volumes:
      - ./app:/app
    depends_on:
      - data

  data:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
